// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article_left_part: typeof import('./src/components/basic/article_page/article_left_part.vue')['default']
    Article_part: typeof import('./src/components/basic/article_page/article_part.vue')['default']
    Article_right_part: typeof import('./src/components/basic/article_page/article_right_part.vue')['default']
    Author_saying: typeof import('./src/components/basic/main_page/author_saying.vue')['default']
    Comment_part: typeof import('./src/components/basic/article_page/comment_part.vue')['default']
    Comment_show: typeof import('./src/components/basic/article_page/comment_show.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Header_img: typeof import('./src/components/basic/theme_component/header_img.vue')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpComment: typeof import('~icons/ep/comment')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    Login: typeof import('./src/components/core/Login.vue')['default']
    Main_first_part: typeof import('./src/components/basic/main_page/main_first_part.vue')['default']
    Main_fourth_part: typeof import('./src/components/basic/main_page/main_fourth_part.vue')['default']
    Main_second_part: typeof import('./src/components/basic/main_page/main_second_part.vue')['default']
    Main_third_part: typeof import('./src/components/basic/main_page/main_third_part.vue')['default']
    Nav_ark: typeof import('./src/components/basic/nav_ark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show_user: typeof import('./src/components/basic/main_page/show_user.vue')['default']
    Show_write: typeof import('./src/components/basic/main_page/show_write.vue')['default']
    'Show——write': typeof import('./src/components/basic/main_page/show——write.vue')['default']
    ShowWrite: typeof import('./src/components/basic/main_page/show-write.vue')['default']
    Title_main: typeof import('./src/components/basic/theme_component/title_main.vue')['default']
    What_is_ark: typeof import('./src/components/basic/main_page/what_is_ark.vue')['default']
  }
}
