// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article_part: typeof import('./src/components/basic/article_page/article_part.vue')['default']
    Carousel: typeof import('./src/components/basic/Carousel.vue')['default']
    Carousel_change: typeof import('./src/components/basic/theme_component/carousel_change.vue')['default']
    Comment_part: typeof import('./src/components/basic/article_page/comment_part.vue')['default']
    copy: typeof import('./src/components/basic/theme_component/header_change copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header_change: typeof import('./src/components/basic/theme_component/header_change.vue')['default']
    Header_img: typeof import('./src/components/basic/theme_component/header_img.vue')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpComment: typeof import('~icons/ep/comment')['default']
    IEpManagement: typeof import('~icons/ep/management')['default']
    IEpPostcard: typeof import('~icons/ep/postcard')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    Login: typeof import('./src/components/core/Login.vue')['default']
    Main_first_part: typeof import('./src/components/basic/main_page/main_first_part.vue')['default']
    Main_fourth_part: typeof import('./src/components/basic/main_page/main_fourth_part.vue')['default']
    Main_second_part: typeof import('./src/components/basic/main_page/main_second_part.vue')['default']
    Main_third_part: typeof import('./src/components/basic/main_page/main_third_part.vue')['default']
    Manager_follow_com: typeof import('./src/components/basic/article_page/manager_follow_com.vue')['default']
    Nav_ark: typeof import('./src/components/basic/nav_ark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title_main: typeof import('./src/components/basic/theme_component/title_main.vue')['default']
  }
}
