// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Author_saying: typeof import('./src/components/basic/main_page/author_saying.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    Login: typeof import('./src/components/core/Login.vue')['default']
    Nav_ark: typeof import('./src/components/basic/nav_ark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show_user: typeof import('./src/components/basic/main_page/show_user.vue')['default']
    Show_write: typeof import('./src/components/basic/main_page/show_write.vue')['default']
    'Show——write': typeof import('./src/components/basic/main_page/show——write.vue')['default']
    ShowWrite: typeof import('./src/components/basic/main_page/show-write.vue')['default']
    What_is_ark: typeof import('./src/components/basic/main_page/what_is_ark.vue')['default']
  }
}
